### ISSUE TITLE
variable "vimeo" is not defined

### ISSUE THREAD

**Issue by Jrizzi1** [dannyrich/CFVimeoAPIWrapper#1]
i do the following:
```
vimeo = createObject("component", "models.vimeoService").init(CLIENT_ID, CLIENT_SECRET);
		vimeo.setToken(ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
```
after setting the static values for those, i get the following
Type: Expression 
Messages: Variable VIMEO is undefined.

i am using localhost to develop, not sure if that makes a difference

**Comment by dannyrich** [comment]
The `init()` method doesn't return anything, so you'll need to split the object creation and init call into two lines:

```cf
vimeo = createObject("component", "models.vimeoService")
vimeo.init(CLIENT_ID, CLIENT_SECRET);
vimeo.setToken(ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
```
