### ISSUE TITLE
<cfset vimeo.init(CLIENT_ID, CLIENT_SECRET)> this gives undefined

### ISSUE THREAD

**Issue by iambasitali** [dannyrich/CFVimeoAPIWrapper#3]
I set vimeo credentials
<cfset CLIENT_ID = "Client ID provided by Vimeo">
<cfset CLIENT_SECRET = "Client secret provided by Vimeo">
<cfset ACCESS_TOKEN = "Access token provided by Vimeo">
but when I dumped <cfset vimeo.init(CLIENT_ID, CLIENT_SECRET)>
it gives me undefined 
on the other side <cfset local.vimeo.setToken(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)> it return 
TRUE.
please look at my issue and give me the solution.
Did only I need to set the above credentials all other things will work?
or we need to set some thing else.

**Comment by dannyrich** [comment]
Dumping `vimio.init(...)` will be undefined because that method doesn't return anything. The data gets stored in the object you created, and you can use that object to call other methods.

```
<cfset vimeo = createObject("component", "VimeoComponent")>
<cfset vimeo.init(CLIENT_ID, CLIENT_SECRET)>
<cfset vimeo.setToken(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)>
<cfset data = vimeo.call(
  "vimeo.videos.getUploaded", 
  { 
    "user_id"=ACCESS_TOKEN, 
    "sort"="newest", 
    "page"="1", 
    "per_page"=PER_PAGE 
  }
) />
```
